### ISSUE TITLE
ALA and GBIF resolvers for GraphQL

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#174]
We would like to refactor the GraphQL project such that you can plugin ALA or GBIF resolvers. That would allow the React UI to use GraphQL, which in turn talks to different backends (ALA or GBIF). Getting this to work is the first step towards a shared UI library.

@jack-brinkman has nicely started that https://github.com/jack-brinkman/gql-resolvers

The next question is how to get it into the gbif-web project. I'm not sure what the best approach is, so here is some ideas.

* The `gql-resolvers` live in a different repo, and we simply refactor `gbif/gbif-web/packages/graphql-api` to use that dependency.
  * So `gbif/gbif-web` + `gbif/gql-resolvers`
* The `gql-resolvers` is merged into the graphql project. So that the code for graphql is managed in one place. It isn't as such necessary to have a separate project for the resolvers.
  * `gbif/gbif-web/packages/graphql-api` is refactored to have multiple resolvers in that project.
* `gql-resolvers` becomes a new package in the mono repo.
  * We have `gbif/gbif-web/packages/graphql-api` + `gbif/gbif-web/packages/gql-resolvers`

Another question is what branch we do want this to go to. I would like to get it into master, but the place we have shared work is in the `joins` branch. And that branch isn't something GBIF is ready to bring into master yet.

ping @djtfmartin and @timrobertson100

**Comment by djtfmartin** [comment]
Thanks @MortenHofft 

Out of those options, i think i'd favour option (2) - so that the code for graphql is managed in one place and we dont over complicated development.

On regarding merging into master i'm struggling to remember the sticking points.
From memory, i think the main issues was with `es-api` and the code in `reduce.js`. 
Its my view that we can have something that is compatible with the current production GBIF ES schema and the new nested schema with either simple checks on the contain (as implemented on `joins` already) or with something more explicit (a config variable e.g.  `nested_schema: true`.

**Comment by jack-brinkman** [comment]
My two cents - I agree that option (2) would be the most straightforward approach in terms of development. If we are to go with option (2):

- Currently, the `gql-resolvers` package uses [ECMAScript module](https://nodejs.org/api/esm.html) syntax. When implementing `gql-resolvers`, we'd need to re-write the server imports using ESM (rather than re-writing all of the resolvers).
- The package also uses TypeScript & absolute imports, which are compiled into regular JS code using the TypeScript compiler.
  - We could either:
    - Revert the absolute imports to relative ones & remove TypeScript capability.
    - Keep the absolute imports & TypeScript capability, and run the project with `ts-node` (to skip needing to compile the project explicitly)
    -  Keep the absolute imports & TypeScript capability, and compile the project files using the TypeScript compiler.
  - I'd lean towards the second option: keeping the absolute imports and running the project with `ts-node`.

To save time making local changes to the `resolvers`, `dataSources` & `typeDefs` files to specify which resolvers to use, we could add a configuration option in the .env file that dictates what to use.

**Comment by MortenHofft** [comment]
Sounds like we all prefer option 2 🎊 

I'm more that happy to move to ES import modules, that would be convenient. 

And I definitely think configuration should be done from the `.env` file.

Absolute imports is also possible without Typescript (we even have it on the gbif.org project, that do not use babel, Webpack or similar). As for Typescript, I'm less enthused, but clearly it motivates you Jack, so let us do that. But perhaps we could do it on such a way that we keep the shared parts and the GBIF resolvers as is, and then you can use typescript in the ALA resolvers? The project as a whole will support it (as in your current `gql-resolvers` project). 

The details not clear to me, but would something along those lines that be okay with you?

**Comment by jack-brinkman** [comment]
That sounds excellent. I'd be happy with the shared & GBIF resolvers remaining as plain JS and the ALA resolvers using TypeScript. Having the project support it still leaves that door open in the future, as type safety is always good to have - what do you think @djtfmartin ?

**Comment by djtfmartin** [comment]
sounds good to me

**Comment by jack-brinkman** [comment]
This as been completed as per #186
