### ISSUE TITLE
Event table crash - measurementOrFaceTypes.name

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#198]
Some issues have arisen with retrieving measurement or fact data for some datasets (i.e. `1436148-trial-164` has attached measurements or facts, but they're not shown in the portal). One effect of this issue is that, in the default table configuration, the measurement or fact type names are concatenated when being formatted as such:

```js
formatter: (value, item) => <>{value.join(', ')}</>
```

However, since null is being returned, the method errors & the portal crashes. A screenshot of the error can be seen below:

![image](https://user-images.githubusercontent.com/104949733/202065187-05a5a59a-e0b7-416a-9b28-b06d4cf9e1ea.png)

**Comment by jack-brinkman** [comment]
Disregard above commit - looks like it's fixed in #197

**Comment by MortenHofft** [comment]
Is the mentioned fix? https://github.com/gbif/gbif-web/pull/197/commits/4150c414873ab149afbd48fb29bb053ff92cd7d5
That looks wrong to me.

That being said it is clearly a bug.
The schema says to expect nulls https://github.com/gbif/gbif-web/blob/master/packages/graphql-api/src/resources/shared/resources/event/event.type.js#L88 but we do not. So good thing to add it.

We could also consider changing it in the index or es-api so that we could update the schema to `[String]!`?

**Comment by djtfmartin** [comment]
this was fixed in #204
