### ISSUE TITLE
Configurable Queries

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#213]
The ability to change/overwrite queries would assist with some of the more complicated use cases for the hosted portals. I've given some thought as to how this could be implemented simply, yet with enough flexibility for future changes.

My idea (& initial implementation) is to allow instances of the `useQuery` hook (& thereby, the related queries) to be tagged via a `queryTag` config option, allowing them to be modified via the site configuration object. For instance:

```js
const { data, load } = useQuery(OCCURRENCE_GALLERY, { lazyLoad: true, queryTag: 'gallery' });
```

The tagged query can then be modified using the site configuration as such:

```js
{
  locale: 'en',
  occurrence: {
    queries: {
      gallery: '.. my query here ..'
    }
  }
}
```

Tags can be the same across different searches, as it uses `SearchContext` to store the provided query config. Having the tags for the same types of queries across search components will also help with consistency. For example, if I were using both Event & Occurrence search, and wanted different queries for both table components, the config would be as follows:

```js
{
  locale: 'en',
  event: {
    queries: { table: 'event query here' }
  },
  occurrence: {
    queries: { table: 'occurrence query here' }
  }
}
```

In this initial implementation, I've added a helpful `queryTag` property to the `PredicateDataFetcher` & `StandardSearch` components, which is passed along to the `useQuery` hook. I've also added default tags to the `StandardSearchTable` component (`table` & `tableSlow`).

Under the hood, a small change has been made to the `useQuery` hook to check whether the query is tagged, and whether it is configured:

```js
// at top-level of the hook - queries is renamed to queryConfig in the context provider
const { queryConfig } = useContext(SearchContext);

// in the load() function
const { promise: dataPromise, cancel } = client.query({
  query: queryTag ? queryTransform(query, queryConfig, queryTag) : query,
  variables,
  queue
});
```

Note `queryTransform`, which is this simple function that currently just overrides the query:

```js
const isConfigObject = (customConfig) => customConfig?.hasOwnProperty(''); // Placeholder

// This is a placeholder function to handle custom queries.
// Currently, it just overrides the default query with a custom one (if provided),
// however, it will make the query transformations a bit easier
// in the future.
export const queryTransform = (query, queryConfig, queryTag) => {
    const customConfig = queryConfig[queryTag];
    if (isConfigObject(customConfig)) {
      // Do some transformations here here
    } else if (typeof customConfig === 'string') {
      return customConfig; // Just override the query
    }
    
    // Return the original query
    return query;
}
```

It's implemented this way so that this functionality can easily be extended - only `queryTransform.js` needs to be changed.

**Comment by MortenHofft** [comment]
I like the approach - it looks reasonable to me. But I suppose it has little value without the overridable table config. And for that part I'm more in doubt if we are doing it right. https://github.com/gbif/gbif-web/pull/210

The tableConfig increasingly makes use of React syntax and other components. For that reason I've opted to only expose a config for *which* columns to include and the ordering in occurrences. I do not mind exposing the configuration as a whole, but I suspect that it would require a fairly complex configuration. And hence probably a separate build to be a nice experience. And if that is the case, then perhaps we should look into another approach for this as well?

I would like to understand better if the use case is something that benefits event search in general - if so we should include whatever is needed in the default config. If it is something special that doesn't really apply to any other event datasets, then perhaps we shouldn't do it. Instead we could look more into a custom build (instead of the current configuration approach).

It could be ESM build of components as well as the relevant search/entity widgets. And then another project that used the library to create its own widgets, reusing the components that make sense for that very much unique use case? 

I'm raising that as it isn't really clear to me what the general relevance is of this? Could you help @djtfmartin ?

**Comment by MortenHofft** [comment]
@jack-brinkman I just tried to run the branch feature/configurable-queries locally. I cannot get it to work. all search views seem to fail

**Comment by jack-brinkman** [comment]
@MortenHofft You're right - there was a small typo. I just pushed a fix, then :)

The usage of the query overriding is detailed in the thread above - the table config can be overridden with the `tableConfig` property in the site configuration, i.e.

```js
const alaSiteConfig = {
  locale:'en',
  event: {
    tableConfig: {
      columns: [
        {
          trKey: 'filters.eventType.name',
          value: {
            key: 'eventType.concept',
            hideFalsy: true,
          },
        },
        // .. more here ...
      ]
    }
  }
}
