### ISSUE TITLE
support multi-configurations

### ISSUE THREAD

**Issue by qifeng-bai** [gbif/gbif-web#280]
Events App loads the configurations from .env.json, its file path is hardcoded. It would be more convenient if we is able to configure our application for multiple environments and allow the application to behave differently for each environment such as development, test, stage, production.

Plan:
Create an Env alias linked to different .env.json, .env.production.json in storybook.js and main.js 

Current implementation has some Limitations :
     in package.json:
     1, Build process only supports via argv:
        "build": "npx webpack --mode=production",
        "build:test": "npx webpack --mode=development",

     2, Running process only supports via Env
           "start": "cross-env NODE_ENV=development node locales/build.js; start-storybook -p 6006;",

     3, if the corresponding json, e.g .env.production.json, is not found, use the default .env.json file

**Comment by qifeng-bai** [comment]
pr: https://github.com/gbif/gbif-web/pull/285

**Comment by MortenHofft** [comment]
The react components are in the process of being replaced with a merged codebase between hosted portals and gbif.org. 

That said I like the idea of just being able to take the library and define the endpoints dynamically. In practice I find it to be annoying as well as everything is then a context. Which can be awkward for some use cases where you just need an endpoint without a react context. 
And it is often not the case that you can just move to another environment since the APIs, graphql schemas and ui library are closely tied so it would often fail if trying to use another env.
I'm not sure I like it. Even if it is annoying to do a new build for a new env
